### ISSUE TITLE
Package for CentOS 7

### ISSUE THREAD

**Issue by pandreetto** [EGI-Federation/nagios-plugins-bdii#1]
Reference: https://ggus.eu/index.php?mode=ticket_info&ticket_id=136695

The structure of rpm must be compliant with ARGO guidelines:
https://docs.google.com/document/d/1fDqO0LPjRlX68D_jDm3ulxsc0J17XoZqAjMnjRhDfHI/edit

**Comment by pandreetto** [comment]
The probe is very simple. Rebuilding the source rpm for SL6 seems to work fine also on CentOS 7.
The structure is compliant with ARGO guidelines (Section packaging, footnote 6).
No temporary files are produced; no configuration files are required.
There's something wrong with the version number, the release in EPEL6 is 1.0.14, but in the code I see a 1.0.15. I've got to investigate

**Comment by gwarf** [comment]
HI @pandreetto, I can submit a PR to provide build instructions similar to what is done for https://github.com/EGI-Foundation/glite-info-update-endpoints.
I think it's quite handy to be able to create native packages, and as it runs in a container it's easy to get it integrated in a CI.

**Comment by pandreetto** [comment]
You're right, it's better to use the same technique for all the components.
I see that even the build of the glue-validator follows this idea.
